"use client";

import {
  ListChecks,
  DraftingCompass,
  Code2,
  ScanSearch,
  FlaskConical,
  Bug,
  ShieldCheck,
  BookOpen,
  Package,
  GitBranch,
  Box,
  Cpu,
  FolderTree,
  Smartphone,
  LayoutTemplate,
  ShieldAlert,
  Database,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  "list-checks": ListChecks,
  "drafting-compass": DraftingCompass,
  code: Code2,
  "scan-search": ScanSearch,
  "flask-conical": FlaskConical,
  bug: Bug,
  "shield-check": ShieldCheck,
  "book-open": BookOpen,
  package: Package,
  "git-branch": GitBranch,
  box: Box,
  cpu: Cpu,
  "folder-tree": FolderTree,
  smartphone: Smartphone,
  "layout-template": LayoutTemplate,
  "shield-alert": ShieldAlert,
  database: Database,
};
